### ISSUE TITLE
Adding WebView screen for opening links 

### ISSUE THREAD

**Issue by hridayK** [Subhradeep10/DevAcademy#11]
Adding a view web view screen for opening user screen will make for a smoother experience for the user to access resources, and the user will not have to open a browser tab for viewing any resources that are redirected at.

**Comment by Subhradeep10** [comment]
@hridayK go ahead, assigned to you

**Comment by Subhradeep10** [comment]
@hridayK any update?

**Comment by hridayK** [comment]
sorry, haven't been able to start work on it due to a few unexpected college deadlines, will definitely implement it by this weekend

**Comment by hridayK** [comment]
![image](https://user-images.githubusercontent.com/16136188/184854804-fdd7be4a-9d04-4351-8e58-a8f6d3b55c51.png)
Update started working on web view integration
