### ISSUE TITLE
DevAcademy AppBar Back button

### ISSUE THREAD

**Issue by venkey-dev** [Subhradeep10/DevAcademy#12]
The app doesn't need any back button on the app bar on the home screen of the application.
Assign me this issue.

**Comment by Subhradeep10** [comment]
@venkat-clone Go ahead assigned to yo

**Comment by mdnazisharman2803** [comment]
@Subhradeep10  kindly give me the access to this repo as i am mentor so i can assign issue to contributors

**Comment by nigeldias27** [comment]
Can I work on this? @mdnazisharman2803 @Subhradeep10

**Comment by mdnazisharman2803** [comment]
@nigeldias27  already assigned.. Wait for 5_7 more days if no any response, you can work on it.. Meanwhile you can look into other issue in app, you can create and I'll assign it to you
