### ISSUE TITLE
Removing the view more button

### ISSUE THREAD

**Issue by nigeldias27** [Subhradeep10/DevAcademy#14]
I was thinking about removing the view more button and making the whole card clickable using Inkwell to make it more minimalistic like this:
![splash](https://user-images.githubusercontent.com/41966681/184622041-eddf1976-4a4c-4803-a7fd-c7f0d811127f.gif)

**Comment by mdnazisharman2803** [comment]
@nigeldias27  the changes you requested is looking nice.. It will be nicer if you can add bit animation to that card.. let's wait for @Subhradeep10  approval

**Comment by nigeldias27** [comment]
Definitely. Maybe I could add an Open container and hero widget to give it this effect:
![1*KWIqpb5G2U7WfkXWjHmb-Q](https://user-images.githubusercontent.com/41966681/184684919-9cb8b4dc-3050-4f81-83ba-1b98a06d480e.gif)

**Comment by Subhradeep10** [comment]
Great @nigeldias27 Go ahead , start working
