### ISSUE TITLE
Merge conflict issue

### ISSUE THREAD

**Issue by nigeldias27** [Subhradeep10/DevAcademy#17]
While resolving a merge conflict, the changes I have made in #16 have come undone. Can I fix this?

**Comment by nigeldias27** [comment]
@mdnazisharman2803

**Comment by mdnazisharman2803** [comment]
> @mdnazisharman2803

Make a proper issue and then I'll assign you.. Explaining what you'll work

**Comment by nigeldias27** [comment]
Currently the home page looks like this
![home](https://user-images.githubusercontent.com/41966681/185790966-1c6a4641-d00e-47dd-8a21-ec1c0469b22f.png)
and when the card is clicked it goes to each individual page where the entire card is clickable(when it is clicked, it will open the link in the chrome browser) as well as the view button is present(when it is clicked, it will open the link in web view)
![heading](https://user-images.githubusercontent.com/41966681/185791026-db89149c-5601-4184-a4f6-9a6ba38e8901.png)

I would like to change it so that when the entire card is clicked it opens the link in web view and would like to remove the view button

**Comment by bhattabhi013** [comment]
This issue is fixed.

**Comment by nigeldias27** [comment]
The SSOC labels were not added to this issue. @mdnazisharman2803
