### ISSUE TITLE
Update the logo 

### ISSUE THREAD

**Issue by Subhradeep10** [Subhradeep10/DevAcademy#2]
![DevAcademy](https://user-images.githubusercontent.com/70656957/179785072-e47d0c0b-e34d-494d-b0ed-7b5b70d22d76.png)

**Comment by roshhni97** [comment]
@Subhradeep10 Can I work on this ?

**Comment by Subhradeep10** [comment]
@Roshani9731 Go ahead, assigned to you

**Comment by Subhradeep10** [comment]
@Roshani9731 Any update?

**Comment by roshhni97** [comment]
I am still trying.

**Comment by roshhni97** [comment]
I have to change app icon write?

**Comment by Subhradeep10** [comment]
@Roshani9731 Yes

**Comment by yk3066** [comment]
If this issue is unassigned can i work on it, although there was a problem with running the app on emulator on android studio.

**Comment by Subhradeep10** [comment]
@yk3066 Sure go ahead, assigned to you

**Comment by yk3066** [comment]
Logo added to the app.
![Screenshot_1659550590](https://user-images.githubusercontent.com/59407464/182680730-e774dcbb-cce0-4eb5-bd02-b61da37c8fc3.png)

**Comment by Subhradeep10** [comment]
Great, now create the PR

**Comment by mdnazisharman2803** [comment]
@Subhradeep10  kindly close this issue as it has been fixed.

**Comment by Subhradeep10** [comment]
@mdnazisharman2803 Yeah thanks for reminding!
