### ISSUE TITLE
Webview for Flutter web

### ISSUE THREAD

**Issue by nigeldias27** [Subhradeep10/DevAcademy#20]
Webview is not supported for Flutter web. If you run it on the web this error appears:
<img width="1199" alt="Screenshot 2022-09-01 at 12 16 10 PM" src="https://user-images.githubusercontent.com/41966681/187853879-34df4e78-6241-4e77-85aa-1b76e938f6e3.png">

So I would like to add a condition, if the app is being run on the web then url is launched in a new tab(using url_launcher library). Otherwise it will use the Webview widget.

**Comment by nigeldias27** [comment]
@mdnazisharman2803

**Comment by mdnazisharman2803** [comment]
@nigeldias27  done

**Comment by nigeldias27** [comment]
SSOC labels have not been added to this issue
