### ISSUE TITLE
Update the UI

### ISSUE THREAD

**Issue by Subhradeep10** [Subhradeep10/DevAcademy#3]
Our app has been featured in product hunt, Kindly upvote it and add this Prodct hunt logo there

<a href="https://www.producthunt.com/posts/devacademy?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-devacademy" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=353035&theme=light" alt="DevAcademy - A&#0032;specialized&#0032;app&#0032;for&#0032;developers | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>

**Comment by tanishgoyal07** [comment]
Can you please elaborate more to what to do here , I want to work on it

**Comment by Subhradeep10** [comment]
@Subhradeep10 Update this image, so that it will redirect to the product hunt page

**Comment by anisha-01-phoenix** [comment]
Hi @Subhradeep10 , I would like to work on this issue. Please assign it to me.

**Comment by Subhradeep10** [comment]
@anisha-01-phoenix go ahead, will assign it to you once the program starts

**Comment by Subhradeep10** [comment]
@anisha-01-phoenix Go ahead, Start working on it..Assigned to you
